services:
  - type: web
    name: xp-dashboard
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: xp-dashboard-db
          property: connectionString
      - key: VITE_API_URL
        fromService:
          type: web
          name: xp-dashboard
          property: url

databases:
  - name: xp-dashboard-db
    databaseName: xp_dashboard
    user: xp_dashboard
    plan: starter
